### ISSUE TITLE
Applying Filter on 'Required Clearance' field includes other items with similar text

### ISSUE THREAD

**Issue by djmaso** [djmaso/career-portal#1]
I updated the sidebar-filter to include another field available through the API, customText3. 

## Current behavior

- Required clearance pulls in values from customText3.
- Clicking on a value such as 'TS' will also include other values including 'TS'. So, there are currently only 3 matches to 'TS' but when I select 'TS', it also includes values such as 'TS SCI', 'TS SCI with FS Poly', and 'TS SCI with CI Poly'.

## Expected behavior

- When selecting a filter, it should only show Open Positions matching that filter specifically.

## Steps to replicate behavior

1. Update these values in the app.json config to run against our API
   "corpToken": "7T1XS1"
   "swimlane": "32"
2. I compile and run the project by executing 'npm run serve'.
3. Browse to localhost:4200.
4. Filter by 'TS' in Required Security Clearance.
5. Filtered results under Open Positions should only reflect the number of results highlighted. In the screenshot, it should only be 3 results.

## Screenshots

![image](https://user-images.githubusercontent.com/112977471/192820086-6e2c551c-15b4-4a29-b355-631adc432a82.png)

**Comment by ReethuVinta** [comment]
I'm not able to see this experience as the Required Clearance is not having any checkboxes. Can you update the data?

**Comment by djmaso** [comment]
I updated the app.json to point to my data and now it shows the appropriate field for Required Clearance.

**Comment by FinnHering** [comment]
Hey there, 
I was able to fix this issue by changing the request to be sent to /query instead of /search. The /search endpoint is not capable of searching for exact matches without doing complex changes to the website. The /query endpoint on the other hand is able to do that. 
Everything works like before, except that all filters now have to match exactly (including the filter for 'TS'). 
This is the related PR: #2

**Comment by djmaso** [comment]
Thank you very much for your help in resolving this for me. I wish you the very best!
